# Generated by Django 4.2 on 2024-07-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailPoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name=255)),
                ('phone', models.CharField(verbose_name=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('salespoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.retailpoint')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.worker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='retailpoint',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.worker'),
        ),
    ]
