# Generated by Django 4.2 on 2024-07-15 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit",
            old_name="salespoint",
            new_name="retail_point",
        ),
        migrations.AlterField(
            model_name="retailpoint",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="retailpoint",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visit",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="visit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="worker",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
